# Generated by Django 4.2.1 on 2023-05-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('SAS', 'SAS'), ('SITE', 'SITE'), ('V-SIGN', 'V-SIGN'), ('SSL', 'SSL'), ('SENSE', 'SENSE'), ('SCE', 'SCE'), ('SBST', 'SBST'), ('VAIAL', 'VAIAL'), ('VIT BS', 'VIT BS'), ('SCOPE', 'SCOPE'), ('V-SPARC', 'V-SPARC'), ('SMEC', 'SMEC'), ('SELECT', 'SELECT'), ('SCHEME', 'SCHEME'), ('HOT', 'HOT')], max_length=100)),
                ('credits_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('moduel_no', models.IntegerField()),
                ('topics', models.CharField(max_length=500)),
                ('links', models.URLField()),
                ('notes', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
