# Generated by Django 4.2.1 on 2023-05-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='moduel_no',
            new_name='module_no',
        ),
    ]
